version: '3.8'

services:
  frontend:
    # image: todayeatwhat/frontend:latest
    build: ./frontend
    ports:
      - "0.0.0.0:3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://0.0.0.0:4000
      - REACT_APP_API_URL_FALLBACK=http://localhost:4000

  backend:
    # image: todayeatwhat/backend:latest
    build: ./backend
    ports:
      - "0.0.0.0:4000:4000"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/todayeatwhat
      - PORT=4000

  mongodb:
    image: mongo:latest
    ports:
      - "0.0.0.0:27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: 