version: '3.8'

services:
  frontend:
    image: todayeatwhat/frontend:latest
    ports:
      - "0.0.0.0:3000:3000"
    environment:
      - REACT_APP_API_URL=http://172.18.127.83:4000
      - REACT_APP_API_URL_FALLBACK=http://localhost:4000

  backend:
    image: todayeatwhat/backend:latest
    ports:
      - "0.0.0.0:4000:4000"
    environment:
      - PORT=4000